### ISSUE TITLE
Compare WRF profile with sonde data

### ISSUE THREAD

**Issue by zxdawn** [blaylockbk/Ute_WRF#1]
As mentioned in the [wiki](https://github.com/blaylockbk/Ute_WRF/wiki), 
> vert_profile.py creates vertical profiles at a station defined from the tslist.

Is that possible to compare WRF output file with sonde data (lon,lat,height, *variables*)?
I can't find the `vert_profile.py` in this repository.

If that's possible, could you share that code again?
Thanks!

**Comment by blaylockbk** [comment]
Hi @zxdawn ,
I'm sorry, but I haven't maintained this code in over 4 years and haven't been able to locate that particular file. I edited the wiki so it doesn't mention that file anymore.

Instead, this might be of use to you...though it, too, is several years old... [WRF_timeseries.py](https://github.com/blaylockbk/pyBKB_v2/blob/8d061bdbfbcc03ec64ad4625a06b8380571b099d/BB_WRF/WRF_timeseries.py).

As for plotting sounding data, I recommend using [MetPy](https://unidata.github.io/MetPy/latest/)

**Comment by zxdawn** [comment]
Hi @blaylockbk , Thank you for your response. It's very helpful! I will try Metpy and that script.
